# Generated by Django 2.2.4 on 2019-08-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('indent_number', models.AutoField(primary_key=True, serialize=False)),
                ('bid_Subject', models.CharField(max_length=1000)),
            ],
        ),
    ]
