# Generated by Django 2.2.5 on 2019-09-23 04:46

import createbid.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('indent_number', models.IntegerField(default=createbid.models.increment_indent_number, primary_key=True, serialize=False)),
                ('bid_subject', models.TextField()),
                ('bid_type', models.CharField(choices=[('LTE', 'LTE'), ('LTE-eproc', 'LTE-eproc'), ('OpenTender', 'OpenTender'), ('Ammendment', 'Ammendment'), ('SpotQuotation', 'SpotQuotation'), ('SingleTender', 'SingleTender')], default='LTE', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='proposalNoteSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estCost', models.FloatField()),
                ('gstIncl', models.BooleanField()),
                ('noteDate', models.DateField()),
                ('noteApprovedDate', models.DateField(null=True)),
                ('noteBy', models.CharField(max_length=100)),
                ('notebyDesg', models.CharField(max_length=100)),
                ('bidopendays', models.IntegerField(default=21)),
                ('completionterms', models.TextField()),
                ('tenderCategory', models.CharField(max_length=100)),
                ('productCategory', models.CharField(max_length=100)),
                ('engineerIncharge', models.CharField(max_length=100)),
                ('addressConsignee', models.CharField(max_length=100)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='createbid.Bid')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposalRefNo', models.CharField(max_length=100)),
                ('proposalDate', models.DateField()),
                ('proposalRecievedDate', models.DateField()),
                ('indentDept', models.CharField(max_length=100)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='createbid.Bid')),
            ],
        ),
        migrations.CreateModel(
            name='EprocTender',
            fields=[
                ('etNo', models.IntegerField(default=createbid.models.increment_et_number, primary_key=True, serialize=False)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='createbid.Bid')),
            ],
        ),
        migrations.CreateModel(
            name='OpenTender',
            fields=[
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='createbid.Bid')),
                ('et', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='createbid.EprocTender')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='createbid.Proposal')),
                ('proposalnotesheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='createbid.proposalNoteSheet')),
            ],
        ),
    ]
