# Generated by Django 2.2.4 on 2019-08-13 06:56

import createbid.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_Subject',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_subject',
            field=models.TextField(default='Procurement'),
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_type',
            field=models.CharField(choices=[('LTE', 'LTE'), ('OpenTender', 'OpenTender'), ('Ammendment', 'Ammendment'), ('SpotQuotation', 'SpotQuotation'), ('SingleTender', 'SingleTender')], default='LTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='bid',
            name='indent_number',
            field=models.IntegerField(default=createbid.models.increment_indent_number, primary_key=True, serialize=False),
        ),
    ]
