# Generated by Django 3.1.5 on 2021-02-22 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0002_auto_20210131_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='completionperiod',
            field=models.CharField(default='30 Days', max_length=150),
        ),
        migrations.CreateModel(
            name='contractAward',
            fields=[
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='createbid.bid')),
                ('typeofaward', models.CharField(default='LOA', max_length=150)),
                ('referenceNo', models.CharField(default='LOA', max_length=150)),
                ('awardedDate', models.DateField(blank=True, default=None, null=True)),
                ('contractStartDate', models.DateField(blank=True, default=None, null=True)),
                ('contractEndDate', models.DateField(blank=True, default=None, null=True)),
                ('estCost', models.FloatField()),
                ('estGstIncl', models.BooleanField()),
                ('awardedAmount', models.FloatField()),
                ('awardedGstIncl', models.BooleanField()),
                ('cpg', models.CharField(default='No CPG/SD', max_length=150)),
                ('awardedVendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createbid.vendor')),
            ],
        ),
    ]
