# Generated by Django 2.2.5 on 2019-11-20 09:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0003_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='emailids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=[], size=None),
            preserve_default=False,
        ),
    ]
