# Generated by Django 2.2.5 on 2019-11-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0004_vendor_emailids'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='blacklisted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='remarks',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
