# Generated by Django 2.2.5 on 2019-11-25 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0006_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.CreateModel(
            name='Indenter',
            fields=[
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='createbid.Bid')),
                ('indenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createbid.Employee')),
            ],
        ),
    ]
