# Generated by Django 2.2.5 on 2019-11-26 06:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0007_auto_20191125_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='TECC',
            fields=[
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='createbid.Bid')),
                ('candmMem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teccandMem', to='createbid.Employee')),
                ('fandMem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecfandaMem', to='createbid.Employee')),
                ('indentMem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecindentMem', to='createbid.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='QR',
            fields=[
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='createbid.Bid')),
                ('qrdate', models.DateField(default=datetime.date.today)),
                ('candmMem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcandMem', to='createbid.Employee')),
                ('fandMem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrfandaMem', to='createbid.Employee')),
                ('indentMem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrindentMem', to='createbid.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='BODC',
            fields=[
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='createbid.Bid')),
                ('candmMem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodcandMem', to='createbid.Employee')),
                ('fandMem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodfandaMem', to='createbid.Employee')),
                ('indentMem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodindentMem', to='createbid.Employee')),
            ],
        ),
    ]
