# Generated by Django 2.2.5 on 2019-11-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0008_bodc_qr_tecc'),
    ]

    operations = [
        migrations.AddField(
            model_name='otproposalnotesheet',
            name='completionperiod',
            field=models.FloatField(default=1.0),
        ),
    ]
