# Generated by Django 2.2.5 on 2019-11-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0009_otproposalnotesheet_completionperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr',
            name='maatvalue',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qr',
            name='oneordervalue',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qr',
            name='threeordervalue',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qr',
            name='twoordervalue',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
