# Generated by Django 2.2.5 on 2019-11-26 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0010_auto_20191126_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qr',
            old_name='fandMem',
            new_name='fandaMem',
        ),
    ]
