# Generated by Django 2.2.5 on 2019-11-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0011_auto_20191126_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr',
            name='qrapproveddate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
