# Generated by Django 2.2.5 on 2019-11-27 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0012_qr_qrapproveddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodc',
            old_name='fandMem',
            new_name='fandaMem',
        ),
        migrations.RenameField(
            model_name='tecc',
            old_name='fandMem',
            new_name='fandaMem',
        ),
    ]
