# Generated by Django 2.2.5 on 2019-11-28 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0013_auto_20191127_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createbid.Bid')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createbid.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='LteDetails',
            fields=[
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='createbid.Bid')),
                ('estCost', models.FloatField()),
                ('gstIncl', models.BooleanField()),
                ('emdwaivedoff', models.BooleanField()),
                ('notedate', models.DateField()),
                ('noteby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createbid.Employee')),
            ],
        ),
    ]
