# Generated by Django 2.2.5 on 2019-12-02 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0014_ltedetails_vendorbid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LteEprocDetails',
            fields=[
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='createbid.Bid')),
                ('estCost', models.FloatField()),
                ('gstIncl', models.BooleanField()),
                ('emdwaivedoff', models.BooleanField()),
                ('notedate', models.DateField()),
                ('noteby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createbid.Employee')),
            ],
        ),
    ]
