# Generated by Django 2.2.5 on 2019-12-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0015_lteeprocdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cpp',
            field=models.BooleanField(default=False),
        ),
    ]
