# Generated by Django 2.2.5 on 2019-12-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0016_vendor_cpp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltedetails',
            name='tendertype',
            field=models.CharField(default='supply', max_length=50),
        ),
    ]
