# Generated by Django 2.2.5 on 2019-12-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0017_ltedetails_tendertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltedetails',
            name='completionperiod',
            field=models.CharField(default='45 Days', max_length=100),
        ),
    ]
