# Generated by Django 2.2.5 on 2019-12-09 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0018_ltedetails_completionperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='LteGeneralConditions',
            fields=[
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='createbid.Bid')),
                ('proposalnoteapproveddt', models.DateField()),
                ('boddt', models.DateField()),
                ('specialconditions', models.BooleanField()),
                ('scopeofwork', models.BooleanField()),
                ('scopeofworkText', models.CharField(max_length=50000)),
                ('paymentterms', models.BooleanField()),
                ('paymenttermsText', models.CharField(max_length=50000)),
                ('contractperiod', models.BooleanField()),
                ('deliveryperiod', models.BooleanField()),
                ('delivaryperiodText', models.CharField(max_length=50000)),
                ('pricebasis', models.BooleanField()),
                ('pricebasisText', models.CharField(max_length=50000)),
                ('validity', models.BooleanField()),
                ('validityText', models.CharField(max_length=50000)),
                ('taxesandduties', models.BooleanField()),
                ('taxesanddutiestext', models.CharField(max_length=50000)),
                ('warranty', models.BooleanField()),
                ('warrantyText', models.CharField(max_length=50000)),
                ('cpg', models.BooleanField()),
                ('cpgText', models.CharField(max_length=50000)),
                ('sd', models.BooleanField()),
                ('sdText', models.CharField(max_length=50000)),
                ('ld', models.BooleanField()),
                ('ldText', models.CharField(max_length=50000)),
                ('qv', models.BooleanField()),
                ('qvText', models.CharField(max_length=50000)),
                ('arbitration', models.BooleanField()),
                ('arbitrationText', models.CharField(max_length=50000)),
                ('officerincharge', models.BooleanField()),
                ('officerinchargeText', models.CharField(max_length=50000)),
            ],
        ),
    ]
