# Generated by Django 2.2.5 on 2019-12-10 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0021_auto_20191209_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedDate',
            fields=[
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='createbid.Bid')),
                ('issueddate', models.DateField()),
            ],
        ),
    ]
