# Generated by Django 2.2.5 on 2019-12-12 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0022_issueddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpDates',
            fields=[
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='createbid.Bid')),
                ('issueddate', models.DateField()),
                ('boddate', models.DateField(blank=True, default=None, null=True)),
                ('bidsubdate', models.DateField(blank=True, default=None, null=True)),
                ('prebiddate', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='IssuedDate',
        ),
    ]
