# Generated by Django 2.2.5 on 2019-12-16 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0023_auto_20191212_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstImpDates',
            fields=[
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='createbid.Bid')),
                ('issueddate', models.DateField()),
                ('boddate', models.DateField(blank=True, default=None, null=True)),
                ('bidsubdate', models.DateField(blank=True, default=None, null=True)),
                ('prebiddate', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Corrigenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50000)),
                ('reason', models.CharField(max_length=50000)),
                ('issueddate', models.DateField()),
                ('boddate', models.DateField(blank=True, default=None, null=True)),
                ('bidsubdate', models.DateField(blank=True, default=None, null=True)),
                ('prebiddate', models.DateField(blank=True, default=None, null=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createbid.Bid')),
                ('issuedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuedby', to='createbid.Employee')),
            ],
        ),
    ]
