# Generated by Django 2.2.5 on 2019-12-17 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0024_corrigenda_firstimpdates'),
    ]

    operations = [
        migrations.CreateModel(
            name='participatedBidders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(max_length=10000)),
                ('emddetail', models.CharField(default='emdwaivedoff', max_length=100)),
                ('docfee', models.CharField(default='free', max_length=100)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createbid.Bid')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createbid.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='biddersquotedetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoteamount', models.FloatField()),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createbid.Bid')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createbid.Vendor')),
            ],
        ),
    ]
