# Generated by Django 2.2.5 on 2020-01-07 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0025_biddersquotedetails_participatedbidders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loapovetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awardquoteamount', models.FloatField()),
                ('awardgstincl', models.BooleanField()),
                ('ndaclause', models.BooleanField()),
                ('saclause', models.BooleanField()),
                ('cpgclause', models.BooleanField()),
                ('specialconditions', models.BooleanField()),
                ('typeofaward', models.CharField(max_length=20)),
                ('loaapproveddate', models.DateField()),
                ('awardvendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createbid.Vendor')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createbid.Bid')),
            ],
        ),
        migrations.CreateModel(
            name='loagcc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scopeofwork', models.BooleanField()),
                ('scopeofworkText', models.CharField(max_length=50000)),
                ('emd', models.BooleanField(default=False)),
                ('emdText', models.CharField(default=' ', max_length=50000)),
                ('paymentterms', models.BooleanField()),
                ('paymenttermsText', models.CharField(max_length=50000)),
                ('contractperiod', models.BooleanField()),
                ('contractperiodText', models.CharField(default=' ', max_length=50000)),
                ('deliveryperiod', models.BooleanField()),
                ('delivaryperiodText', models.CharField(max_length=50000)),
                ('pricebasis', models.BooleanField()),
                ('pricebasisText', models.CharField(max_length=50000)),
                ('validity', models.BooleanField()),
                ('validityText', models.CharField(max_length=50000)),
                ('taxesandduties', models.BooleanField()),
                ('taxesanddutiestext', models.CharField(max_length=50000)),
                ('warranty', models.BooleanField()),
                ('warrantyText', models.CharField(max_length=50000)),
                ('cpg', models.BooleanField()),
                ('cpgText', models.CharField(max_length=50000)),
                ('sd', models.BooleanField()),
                ('sdText', models.CharField(max_length=50000)),
                ('ld', models.BooleanField()),
                ('ldText', models.CharField(max_length=50000)),
                ('qv', models.BooleanField()),
                ('qvText', models.CharField(max_length=50000)),
                ('arbitration', models.BooleanField()),
                ('arbitrationText', models.CharField(max_length=50000)),
                ('officerincharge', models.BooleanField()),
                ('officerinchargeText', models.CharField(max_length=50000)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createbid.Bid')),
            ],
        ),
    ]
