# Generated by Django 2.2.5 on 2020-01-07 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0026_loagcc_loapovetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loagcc',
            name='bid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='createbid.Bid'),
        ),
        migrations.AlterField(
            model_name='loapovetting',
            name='bid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='createbid.Bid'),
        ),
    ]
