# Generated by Django 2.2.5 on 2020-01-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0027_auto_20200107_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='loapovetting',
            name='tecdate',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
