# Generated by Django 2.2.5 on 2020-01-10 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0028_loapovetting_tecdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LteEprocNitDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineerincharge_type', models.CharField(max_length=100)),
                ('engineerincharge_desg', models.CharField(max_length=100)),
                ('engineerincharge_dept', models.CharField(max_length=100)),
                ('addressconsignee_desg', models.CharField(max_length=100)),
                ('addressconsignee_dept', models.CharField(max_length=100)),
                ('proposalapprovedDate', models.DateField()),
                ('tender_category', models.CharField(max_length=100)),
                ('product_category', models.CharField(max_length=100)),
                ('type_of_contract', models.CharField(max_length=100)),
                ('bid_valid_days', models.IntegerField()),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='createbid.Bid')),
            ],
        ),
    ]
