# Generated by Django 2.2.5 on 2020-01-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0030_lteeprocdetails_completionperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='indentDesignation',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
