# Generated by Django 2.2.5 on 2020-01-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0032_auto_20200121_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='indentDesignation',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
