# Generated by Django 2.2.5 on 2020-01-27 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0034_auto_20200124_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='participatedbidders',
            name='qualififed',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='EprocDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecdate', models.DateField(blank=True, default=None, null=True)),
                ('finbidopenapprovaldate', models.DateField(blank=True, default=None, null=True)),
                ('finopendate', models.DateField(blank=True, default=None, null=True)),
                ('tecafterclarrificationdate', models.DateField(blank=True, default=None, null=True)),
                ('clarrificationsentdate', models.DateField(blank=True, default=None, null=True)),
                ('clarrificationlastdate', models.DateField(blank=True, default=None, null=True)),
                ('loapoapproveddate', models.DateField(blank=True, default=None, null=True)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='createbid.Bid')),
            ],
        ),
    ]
