# Generated by Django 2.2.5 on 2020-02-24 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0035_auto_20200127_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participatedbidders',
            old_name='qualififed',
            new_name='qualified',
        ),
    ]
