# Generated by Django 2.2.5 on 2020-03-06 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0037_auto_20200304_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotEnquiryDetails',
            fields=[
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='createbid.Bid')),
                ('engineerInchargeDesignation', models.CharField(max_length=150)),
                ('engineerInchargeDepartment', models.CharField(max_length=150)),
                ('includeSpecialConditions', models.BooleanField()),
                ('enquirydate', models.DateField(blank=True, default=None, null=True)),
                ('bidopeningdate', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='contract_type',
            field=models.CharField(default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='bid',
            name='product_category',
            field=models.CharField(default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='bid',
            name='tender_category',
            field=models.CharField(default='Other', max_length=50),
        ),
    ]
