# Generated by Django 2.2.5 on 2020-03-11 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0038_auto_20200306_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotQuotationCommittee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createbid.Bid')),
                ('committeeMember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committeeMember', to='createbid.Employee')),
            ],
        ),
    ]
