# Generated by Django 2.2.5 on 2020-03-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0040_tenderstages'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_stage',
            field=models.IntegerField(default=0),
        ),
    ]
