# Generated by Django 2.2.5 on 2020-03-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createbid', '0041_bid_bid_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='tenderstages',
            name='main_Stage',
            field=models.BooleanField(default=True),
        ),
    ]
